blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/x03f/nautilustrader-gateio-adapter/issues
    about: For usage questions, open an issue and apply the "question" label.
